"""
Decimal display service -- turning an exact value into a human-readable
string, without ever mutating or replacing the exact value itself.

WHAT IS IT?
-----------
`to_display_string(value, digits)` renders an `ExactNumber` as a decimal
string with a caller-chosen number of digits after the decimal point,
truncating repeating decimals with a trailing ellipsis marker when the
fraction does not terminate at that precision.

WHY DO WE NEED IT?
------------------
The specification is explicit (Section 13): the internal exact value
and the displayed decimal value must be two separate concepts. A user
might want to *see* `33.333333333333333333333333...`, but the engine
must keep computing with `100/3`, not with whatever truncated string was
shown on screen. If display formatting and internal storage were the
same object, increasing "display precision" from 2 to 50 digits would
have no well-defined internal value to fall back to, and worse, a naive
implementation might be tempted to store the *displayed* string as the
source of truth -- exactly the bug this whole project exists to prevent.

HOW DOES IT WORK?
------------------
This is a pure, read-only function: it takes an `ExactNumber`, computes
its decimal expansion to `digits` places using an explicit rounding
step (via `RoundingPolicy.HALF_EVEN` by default, matching standard
mathematical rounding for display purposes only -- this rounding is
*cosmetic*, not a business-rule rounding event, and no `RoundingResult`
is generated by it), and returns a string. It also detects whether the
value is a repeating decimal (`is_repeating`) so API/UI layers can flag
that the displayed digits are an approximation, not the full value.

WHY THIS TECHNOLOGY?
---------------------
Reuses the same `decimal.Decimal` machinery as the rounding service,
but is kept in a separate module because *display formatting* and
*business-rule rounding* are different concerns with different callers,
different audit implications, and different failure modes -- conflating
them would make it easy to accidentally treat a cosmetic display
rounding as if it were an authoritative financial rounding event.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.domain.value_objects.exact_number import ExactNumber
from app.domain.value_objects.rounding_policy import RoundingPolicy
from app.domain.services.rounding_service import round_exact_number


@dataclass(frozen=True, slots=True)
class DisplayResult:
    """A rendered decimal string plus metadata about whether it is exact."""

    text: str
    digits: int
    is_repeating: bool
    is_exact_at_this_precision: bool


def to_display_string(value: ExactNumber, digits: int = 2) -> DisplayResult:
    """Render `value` as a decimal string with `digits` places after the
    point. Does NOT modify `value` -- it always remains available as an
    exact Fraction to the caller.
    """
    if digits < 0:
        raise ValueError("digits must be zero or a positive integer.")

    is_repeating = not value.is_terminating_decimal()
    is_exact_here = (not is_repeating) and _terminates_within(value, digits)

    rounding_result = round_exact_number(value, digits, RoundingPolicy.HALF_EVEN)
    text = str(rounding_result.rounded_value)

    if is_repeating and not is_exact_here:
        text = f"{text}..."

    return DisplayResult(
        text=text,
        digits=digits,
        is_repeating=is_repeating,
        is_exact_at_this_precision=is_exact_here,
    )


def _terminates_within(value: ExactNumber, digits: int) -> bool:
    """True if a *terminating* decimal value fully fits within `digits`
    places (e.g. 1/4 = 0.25 fits within 2 digits but needs 2, not 1,
    to be exact -- 0.2 would already lose information).
    """
    # A terminating fraction's reduced denominator is of the form 2^a * 5^b.
    # It needs max(a, b) decimal digits to be represented exactly.
    denominator = value.denominator
    a = 0
    while denominator % 2 == 0:
        denominator //= 2
        a += 1
    b = 0
    while denominator % 5 == 0:
        denominator //= 5
        b += 1
    if denominator != 1:
        return False  # not terminating at all
    return max(a, b) <= digits
